//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.11 at 08:16:51 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/realdolmen/jxp010/jaxb/domain", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.realdolmen.jxp010.jaxb.domain;
